### ISSUE TITLE
What is CLIP upper bound?How did you get the model?

### ISSUE THREAD

**Issue by PowerKaly** [altndrr/vic#19]
Thank you for your work, I have some questions and hope you can answer them despite your busy schedule
What is CLIP upper bound?How did you get the model?

We consider three main groups of baselines for our comparisons. The most straightforward baselines consist of using CLIP with large vocabularies, such as WordNet [41] (117k names) or the English Words (234k names [16]). As an upper bound, we also consider CLIP with the perfect vocabulary, i.e. the ground-truth names of the target dataset (CLIP upper bound). Due to lack of space, we only report results for CLIP with ViT-L [13].

**Comment by altndrr** [comment]
As you reported, "As an upper bound, we also consider CLIP with the perfect vocabulary, i.e. the ground-truth names of the target dataset (CLIP upper bound).", which means we test CLIP performance on the standard "generalized" zero-shot setting. This means we have a manually-annotated pre-defined list of class names per dataset, not a generated one per image as in the other approaches. Let me know if it is clearer now.
