### ISSUE TITLE
Demo code

### ISSUE THREAD

**Issue by xternalz** [altndrr/vic#2]
Hi, this is a very interesting work and the demo works very well. Would you release the demo code?

**Comment by altndrr** [comment]
Hi, thank you for your interest in our work. The code is available at [hf:altndrr/vic](https://huggingface.co/spaces/altndrr/vic/tree/main). Due to time constraints, the code could be further improved to enhance its readability. Please let me know if you have any questions regarding it.

**Comment by altndrr** [comment]
FYI, we have updated the code of the demo at the link shared earlier, and our model is now available on the transformers library. You can access the inference code by clicking on this repo's [README](https://github.com/altndrr/vic#inference), and the model card can be found at [hf:altndrr/cased](https://huggingface.co/altndrr/cased).
